name: Setup

on:
  workflow_call:
    inputs:
      COMMAND:
        required: true
        type: string

      TYPE:
        type: string

    secrets:
      CACHIX_AUTH_TOKEN:
        required: true

jobs:
  run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v22

      - name: Setup Nix Cache
        uses: cachix/cachix-action@v12
        with:
          name: appist
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Run Command
        run: nix-shell --run "${{ inputs.COMMAND }}"
